2022/05/20 22:42:22 [emerg] 75384#75384: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:42:22 [emerg] 75384#75384: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:42:22 [emerg] 75384#75384: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:42:22 [emerg] 75384#75384: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:42:22 [emerg] 75384#75384: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:42:22 [emerg] 75384#75384: still could not bind()
2022/05/20 22:43:55 [emerg] 75603#75603: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:43:55 [emerg] 75603#75603: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:43:55 [emerg] 75603#75603: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:43:55 [emerg] 75603#75603: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:43:55 [emerg] 75603#75603: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:43:55 [emerg] 75603#75603: still could not bind()
2022/05/20 22:44:37 [emerg] 75676#75676: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:44:37 [emerg] 75676#75676: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:44:37 [emerg] 75676#75676: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:44:37 [emerg] 75676#75676: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:44:37 [emerg] 75676#75676: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:44:37 [emerg] 75676#75676: still could not bind()
2022/05/20 22:45:08 [emerg] 75855#75855: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:08 [emerg] 75855#75855: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:08 [emerg] 75855#75855: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:08 [emerg] 75855#75855: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:08 [emerg] 75855#75855: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:08 [emerg] 75855#75855: still could not bind()
2022/05/20 22:45:11 [emerg] 75859#75859: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:11 [emerg] 75859#75859: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:11 [emerg] 75859#75859: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:11 [emerg] 75859#75859: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:11 [emerg] 75859#75859: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:45:11 [emerg] 75859#75859: still could not bind()
2022/05/20 22:53:13 [emerg] 76638#76638: open() "/var/log/nginx/nginx-access.log" failed (13: Permission denied)
2022/05/20 22:53:17 [emerg] 76647#76647: open() "/var/log/nginx/nginx-access.log" failed (13: Permission denied)
2022/05/20 22:53:40 [emerg] 76682#76682: open() "/log/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:53:41 [emerg] 76685#76685: open() "/log/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:54:08 [emerg] 76740#76740: open() "/logs/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:54:55 [emerg] 76787#76787: open() "/logs/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:54:57 [emerg] 76789#76789: open() "/logs/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:54:58 [emerg] 76792#76792: open() "/logs/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:56:06 [emerg] 76914#76914: open() "/logs/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:56:08 [emerg] 76916#76916: open() "/logs/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:56:22 [emerg] 76942#76942: open() "/logs/nginx-access.log" failed (2: No such file or directory)
2022/05/20 22:58:15 [emerg] 77267#77267: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:58:15 [emerg] 77267#77267: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:58:15 [emerg] 77267#77267: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:58:15 [emerg] 77267#77267: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:58:15 [emerg] 77267#77267: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 22:58:15 [emerg] 77267#77267: still could not bind()
2022/05/20 23:01:33 [emerg] 78820#78820: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:01:33 [emerg] 78820#78820: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:01:33 [emerg] 78820#78820: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:01:33 [emerg] 78820#78820: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:01:33 [emerg] 78820#78820: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:01:33 [emerg] 78820#78820: still could not bind()
2022/05/20 23:04:14 [emerg] 79112#79112: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:04:14 [emerg] 79112#79112: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:04:14 [emerg] 79112#79112: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:04:14 [emerg] 79112#79112: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:04:14 [emerg] 79112#79112: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:04:14 [emerg] 79112#79112: still could not bind()
2022/05/20 23:15:05 [emerg] 81916#81916: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:15:05 [emerg] 81916#81916: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:15:05 [emerg] 81916#81916: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:15:05 [emerg] 81916#81916: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:15:05 [emerg] 81916#81916: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/20 23:15:05 [emerg] 81916#81916: still could not bind()
2022/05/21 20:51:38 [error] 34194#34194: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:51:46 [error] 34194#34194: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:51:46 [error] 34194#34194: *3 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:51:47 [error] 34194#34194: *4 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:51:47 [error] 34194#34194: *5 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:51:49 [error] 34194#34194: *6 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:51:49 [error] 34194#34194: *7 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:52:25 [emerg] 35712#35712: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:25 [emerg] 35712#35712: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:25 [emerg] 35712#35712: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:25 [emerg] 35712#35712: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:25 [emerg] 35712#35712: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:25 [emerg] 35712#35712: still could not bind()
2022/05/21 20:52:36 [emerg] 35726#35726: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:36 [emerg] 35726#35726: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:36 [emerg] 35726#35726: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:36 [emerg] 35726#35726: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:36 [emerg] 35726#35726: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:36 [emerg] 35726#35726: still could not bind()
2022/05/21 20:52:46 [emerg] 35742#35742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:46 [emerg] 35742#35742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:46 [emerg] 35742#35742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:46 [emerg] 35742#35742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:46 [emerg] 35742#35742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:52:46 [emerg] 35742#35742: still could not bind()
2022/05/21 20:53:51 [error] 36213#36213: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:53:52 [error] 36213#36213: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:53:52 [error] 36213#36213: *3 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:47 [error] 36213#36213: *4 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:48 [error] 36213#36213: *5 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:48 [error] 36213#36213: *6 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:49 [error] 36213#36213: *7 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:49 [error] 36213#36213: *8 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:49 [error] 36213#36213: *9 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:50 [error] 36213#36213: *10 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:50 [error] 36213#36213: *11 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:51 [error] 36213#36213: *12 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:51 [error] 36213#36213: *13 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:52 [error] 36213#36213: *14 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:57 [error] 36213#36213: *15 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:58 [error] 36213#36213: *16 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:54:59 [error] 36213#36213: *17 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:56:01 [error] 38490#38490: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:56:02 [error] 38490#38490: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:58:26 [emerg] 39943#39943: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:58:26 [emerg] 39943#39943: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:58:26 [emerg] 39943#39943: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:58:26 [emerg] 39943#39943: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:58:26 [emerg] 39943#39943: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/21 20:58:26 [emerg] 39943#39943: still could not bind()
2022/05/21 20:58:37 [error] 39950#39950: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:58:37 [error] 39950#39950: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:58:49 [error] 41000#41000: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:58:49 [error] 41000#41000: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:58:57 [error] 41000#41000: *3 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:58:58 [error] 41000#41000: *4 failed to load inlined Lua code: content_by_lua(nginx.conf:38):2: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:59:04 [error] 42074#42074: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):3: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:59:05 [error] 42074#42074: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):3: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 20:59:28 [emerg] 43111#43111: unexpected "}" in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:39
2022/05/21 21:00:07 [error] 44234#44234: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):3: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:00:08 [error] 44234#44234: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):3: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:00:53 [error] 45318#45318: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):3: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:00:54 [error] 45318#45318: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):3: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:01:14 [error] 45318#45318: *3 failed to load inlined Lua code: content_by_lua(nginx.conf:38):3: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:01:26 [error] 46386#46386: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:38):5: unexpected symbol near 'local', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:01:27 [error] 46386#46386: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:38):5: unexpected symbol near 'local', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:01:42 [error] 46386#46386: *3 failed to load inlined Lua code: content_by_lua(nginx.conf:38):5: unexpected symbol near 'local', client: 127.0.0.1, server: notes, request: "POST / HTTP/1.1", host: "localhost:8080"
2022/05/21 21:01:43 [error] 46386#46386: *4 failed to load inlined Lua code: content_by_lua(nginx.conf:38):5: unexpected symbol near 'local', client: 127.0.0.1, server: notes, request: "POST / HTTP/1.1", host: "localhost:8080"
2022/05/21 21:01:45 [error] 46386#46386: *5 failed to load inlined Lua code: content_by_lua(nginx.conf:38):5: unexpected symbol near 'local', client: 127.0.0.1, server: notes, request: "POST / HTTP/1.1", host: "localhost:8080"
2022/05/21 21:01:48 [error] 46386#46386: *6 failed to load inlined Lua code: content_by_lua(nginx.conf:38):5: unexpected symbol near 'local', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:08:54 [alert] 49963#49963: worker process 49964 exited on signal 9
2022/05/21 21:09:13 [alert] 49963#49963: worker process 49965 exited on signal 9
2022/05/21 21:09:44 [error] 51111#51111: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:31):2: attempt to call global 'echo' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:31): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/21 21:09:45 [error] 51111#51111: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:31):2: attempt to call global 'echo' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:31): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:17:03 [emerg] 9742#9742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:03 [emerg] 9742#9742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:03 [emerg] 9742#9742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:03 [emerg] 9742#9742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:03 [emerg] 9742#9742: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:03 [emerg] 9742#9742: still could not bind()
2022/05/26 19:17:28 [emerg] 9834#9834: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:28 [emerg] 9834#9834: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:28 [emerg] 9834#9834: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:28 [emerg] 9834#9834: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:28 [emerg] 9834#9834: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:17:28 [emerg] 9834#9834: still could not bind()
2022/05/26 19:40:43 [emerg] 17703#17703: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:40:43 [emerg] 17703#17703: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:40:43 [emerg] 17703#17703: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:40:43 [emerg] 17703#17703: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:40:43 [emerg] 17703#17703: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:40:43 [emerg] 17703#17703: still could not bind()
2022/05/26 19:45:49 [error] 19319#19319: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):5: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:42):5: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:46:18 [emerg] 20406#20406: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:46:18 [emerg] 20406#20406: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:46:18 [emerg] 20406#20406: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:46:18 [emerg] 20406#20406: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:46:18 [emerg] 20406#20406: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 19:46:18 [emerg] 20406#20406: still could not bind()
2022/05/26 19:46:29 [error] 20413#20413: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:46:29 [error] 20413#20413: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:46:30 [error] 20413#20413: *3 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:46:30 [error] 20413#20413: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:46:30 [error] 20413#20413: *5 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:46:31 [error] 20413#20413: *6 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:47:28 [error] 21540#21540: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:47:29 [error] 21540#21540: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:47:30 [error] 21540#21540: *3 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:47:30 [error] 21540#21540: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:13 [error] 21540#21540: *5 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:13 [error] 21540#21540: *6 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:14 [error] 21540#21540: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:14 [error] 21540#21540: *8 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:15 [error] 21540#21540: *9 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:15 [error] 21540#21540: *10 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:15 [error] 21540#21540: *11 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:21 [error] 21540#21540: *12 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:22 [error] 21540#21540: *13 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:47 [error] 21540#21540: *14 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:47 [error] 21540#21540: *15 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:48:47 [error] 21540#21540: *16 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:49:46 [error] 22951#22951: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:35):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:35):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:51:00 [error] 24162#24162: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:51:01 [error] 24162#24162: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:51:38 [error] 25251#25251: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket' not found:
	no field package.preload['socket']
	no file '/usr/local/openresty/site/lualib/socket.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/lualib/socket.ljbc'
	no file '/usr/local/openresty/lualib/socket/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket.lua'
	no file '/usr/local/openresty/site/lualib/socket/init.lua'
	no file '/usr/local/openresty/lualib/socket.lua'
	no file '/usr/local/openresty/lualib/socket/init.lua'
	no file './socket.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/init.lua'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 19:54:39 [error] 26750#26750: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):3: module 'socket.core' not found:
	no field package.preload['socket.core']
	no file '/usr/local/openresty/site/lualib/socket/core.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/core/init.ljbc'
	no file '/usr/local/openresty/lualib/socket/core.ljbc'
	no file '/usr/local/openresty/lualib/socket/core/init.ljbc'
	no file '/usr/local/openresty/site/lualib/socket/core.lua'
	no file '/usr/local/openresty/site/lualib/socket/core/init.lua'
	no file '/usr/local/openresty/lualib/socket/core.lua'
	no file '/usr/local/openresty/lualib/socket/core/init.lua'
	no file './socket/core.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/socket/core.lua'
	no file '/usr/local/share/lua/5.1/socket/core.lua'
	no file '/usr/local/share/lua/5.1/socket/core/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/core.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/socket/core/init.lua'
	no file '/usr/local/openresty/site/lualib/socket/core.so'
	no file '/usr/local/openresty/lualib/socket/core.so'
	no file './socket/core.so'
	no file '/usr/local/lib/lua/5.1/socket/core.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/socket.so'
	no file '/usr/local/openresty/lualib/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:34):3: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:01:48 [error] 29118#29118: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):4: attempt to call field 'tcp' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:34): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:01:49 [error] 29118#29118: *2 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):4: attempt to call field 'tcp' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:34): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:01:49 [error] 29118#29118: *3 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:34):4: attempt to call field 'tcp' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:34): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:08:29 [emerg] 31857#31857: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:08:29 [emerg] 31857#31857: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:08:29 [emerg] 31857#31857: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:08:29 [emerg] 31857#31857: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:08:29 [emerg] 31857#31857: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:08:29 [emerg] 31857#31857: still could not bind()
2022/05/26 20:11:09 [error] 33293#33293: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:11:09 [error] 33293#33293: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:11:14 [error] 33293#33293: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:11:19 [error] 33293#33293: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:11:25 [error] 33293#33293: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:11:30 [error] 33293#33293: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:11:35 [error] 33293#33293: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:12:18 [error] 34550#34550: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:12:18 [error] 34550#34550: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:12:23 [error] 34550#34550: send() failed (111: Connection refused) while resolving, resolver: 127.0.0.11:53
2022/05/26 20:18:54 [error] 39532#39532: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:42):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:18:55 [error] 39532#39532: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:42):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:24:21 [error] 41216#41216: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:42): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:24:22 [error] 41216#41216: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:42): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:24:23 [error] 41216#41216: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:42): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:24:24 [error] 41216#41216: *10 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:42): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:24:24 [error] 41216#41216: *13 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:42): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:24:25 [error] 41216#41216: *16 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:42):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:42): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:27:59 [emerg] 42560#42560: unknown directive "require" in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:27
2022/05/26 20:28:14 [emerg] 42590#42590: unknown directive "require" in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:26
2022/05/26 20:28:16 [emerg] 42592#42592: unknown directive "require" in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:26
2022/05/26 20:28:46 [emerg] 42623#42623: "init_by_lua_block" directive is not allowed here in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:31
2022/05/26 20:29:48 [emerg] 42806#42806: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:29:48 [emerg] 42806#42806: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:29:48 [emerg] 42806#42806: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:29:48 [emerg] 42806#42806: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:29:48 [emerg] 42806#42806: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:29:48 [emerg] 42806#42806: still could not bind()
2022/05/26 20:29:59 [error] 42816#42816: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:43): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:30:00 [error] 42816#42816: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:43): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:30:00 [error] 42816#42816: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: attempt to call field 'send' (a nil value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:43): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:32:54 [error] 44138#44138: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:43):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:32:55 [error] 44138#44138: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:43):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:32:55 [error] 44138#44138: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:43):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:32:56 [error] 44138#44138: *10 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:43):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:32:56 [error] 44138#44138: *13 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:43):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:32:57 [error] 44138#44138: *16 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:43):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:32:58 [error] 44138#44138: *19 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:43):12: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:43):12: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:38 [error] 46341#46341: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:40 [error] 46341#46341: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:42 [error] 46341#46341: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:43 [error] 46341#46341: *10 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:43 [error] 46341#46341: *13 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:44 [error] 46341#46341: *16 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:45 [error] 46341#46341: *19 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:36:50 [error] 46341#46341: *22 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:37:17 [error] 47453#47453: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:37:17 [error] 47453#47453: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:37:18 [error] 47453#47453: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:37:18 [error] 47453#47453: *10 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:37:19 [error] 47453#47453: *13 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:37:19 [error] 47453#47453: *16 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:55 [error] 48778#48778: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:57 [error] 48778#48778: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:57 [error] 48778#48778: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:58 [error] 48778#48778: *10 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:58 [error] 48778#48778: *13 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:58 [error] 48778#48778: *16 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:59 [error] 48778#48778: *19 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:59 [error] 48778#48778: *22 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:38:59 [error] 48778#48778: *25 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:00 [error] 48778#48778: *28 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:03 [error] 48778#48778: *31 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:03 [error] 48778#48778: *34 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:04 [error] 48778#48778: *37 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:04 [error] 48778#48778: *40 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:04 [error] 48778#48778: *43 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: bad argument #1 to 'send' (table expected, got string)
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:22 [error] 49979#49979: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:22 [error] 49979#49979: *4 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:39:23 [error] 49979#49979: *7 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:46):15: expecting 2 arguments (including the object), but got 1
stack traceback:
coroutine 0:
	[C]: in function 'send'
	content_by_lua(nginx.conf:46):15: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 20:52:32 [emerg] 61329#61329: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:52:32 [emerg] 61329#61329: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:52:32 [emerg] 61329#61329: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:52:32 [emerg] 61329#61329: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:52:32 [emerg] 61329#61329: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 20:52:32 [emerg] 61329#61329: still could not bind()
2022/05/26 20:58:36 [error] 63110#63110: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:03:03 [error] 64532#64532: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:03:45 [error] 64532#64532: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:06:01 [error] 66080#66080: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:06:02 [error] 66080#66080: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:06:02 [error] 66080#66080: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:06:03 [error] 66080#66080: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:06:18 [error] 66080#66080: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:06:18 [error] 66080#66080: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:06:44 [error] 67207#67207: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:07:29 [error] 68377#68377: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:07:30 [error] 68377#68377: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:07:31 [error] 68377#68377: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:07:31 [error] 68377#68377: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:07:32 [error] 68377#68377: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:08:01 [error] 68377#68377: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:09:05 [error] 68377#68377: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:11:03 [error] 69996#69996: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:12:13 [error] 71094#71094: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:12:57 [error] 71094#71094: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:12:58 [error] 71094#71094: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:12:59 [error] 71094#71094: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:14:31 [error] 71094#71094: *6 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:18:57 [emerg] 74226#74226: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 21:18:57 [emerg] 74226#74226: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 21:18:57 [emerg] 74226#74226: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 21:18:57 [emerg] 74226#74226: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 21:18:57 [emerg] 74226#74226: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/26 21:18:57 [emerg] 74226#74226: still could not bind()
2022/05/26 21:19:00 [error] 73161#73161: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:60):28: unexpected symbol near '#', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:19:41 [error] 74299#74299: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:20:29 [error] 74299#74299: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:21:09 [error] 75645#75645: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:21:10 [error] 75645#75645: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:21:11 [error] 75645#75645: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:21:12 [error] 75645#75645: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/26 21:22:23 [error] 77878#77878: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 14:43:17 [error] 5117#5117: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 14:49:09 [error] 5117#5117: *3 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 14:53:49 [error] 9122#9122: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:01:04 [error] 9122#9122: *3 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:02:33 [error] 11009#11009: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:04:10 [error] 11009#11009: *3 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:14:51 [error] 13198#13198: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:14:58 [error] 13198#13198: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:15:59 [error] 13198#13198: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:16:00 [error] 13198#13198: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:16:01 [error] 13198#13198: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:16:40 [error] 13198#13198: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:17:58 [error] 13198#13198: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:23:05 [error] 15358#15358: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:23:06 [error] 15358#15358: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:23:07 [error] 15358#15358: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:23:59 [error] 15358#15358: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:29:02 [error] 17131#17131: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:30:45 [error] 18410#18410: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:56):10: attempt to index local 'sock' (a number value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:56): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:31:26 [error] 19560#19560: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:31:26 [error] 19560#19560: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:55):6: connection refused
stack traceback:
coroutine 0:
	[C]: in function 'assert'
	content_by_lua(nginx.conf:55):6: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:31:37 [error] 20611#20611: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:31:37 [error] 20611#20611: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:55):6: connection refused
stack traceback:
coroutine 0:
	[C]: in function 'assert'
	content_by_lua(nginx.conf:55):6: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:31:39 [error] 20611#20611: *3 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:31:39 [error] 20611#20611: *3 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:55):6: connection refused
stack traceback:
coroutine 0:
	[C]: in function 'assert'
	content_by_lua(nginx.conf:55):6: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:31:52 [error] 20611#20611: *5 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:55):10: attempt to index global 'sock' (a number value)
stack traceback:
coroutine 0:
	content_by_lua(nginx.conf:55): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:34:43 [error] 21813#21813: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:35:30 [error] 23184#23184: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:35:32 [error] 23184#23184: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:35:37 [error] 23184#23184: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:35:38 [error] 23184#23184: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:35:39 [error] 23184#23184: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:37:22 [error] 24466#24466: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:38:05 [error] 24466#24466: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:38:06 [error] 24466#24466: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:38:06 [error] 24466#24466: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:38:06 [error] 24466#24466: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:38:07 [error] 24466#24466: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:38:26 [error] 24466#24466: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:39:16 [error] 24466#24466: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:39:17 [error] 24466#24466: *1 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:45:54 [error] 24466#24466: *21 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 15:47:43 [error] 24466#24466: *23 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 16:58:27 [error] 41158#41158: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:69):10: unexpected symbol near '$', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:04:42 [emerg] 47163#47163: is duplicate in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:78
2022/05/27 17:05:26 [emerg] 48248#48248: is duplicate in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:78
2022/05/27 17:05:34 [emerg] 48294#48294: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:05:34 [emerg] 48294#48294: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:05:34 [emerg] 48294#48294: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:05:34 [emerg] 48294#48294: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:05:34 [emerg] 48294#48294: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:05:34 [emerg] 48294#48294: still could not bind()
2022/05/27 17:07:13 [emerg] 51503#51503: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:07:13 [emerg] 51503#51503: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:07:13 [emerg] 51503#51503: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:07:13 [emerg] 51503#51503: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:07:13 [emerg] 51503#51503: bind() to 0.0.0.0:8080 failed (98: Address already in use)
2022/05/27 17:07:13 [emerg] 51503#51503: still could not bind()
2022/05/27 17:09:42 [emerg] 54921#54921: unexpected "}" in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:75
2022/05/27 17:11:09 [error] 56070#56070: *1 lua entry thread aborted: runtime error: attempt to call ngx.redirect after sending out the headers
stack traceback:
coroutine 0:
	[C]: ?, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:11:45 [error] 57147#57147: *1 lua entry thread aborted: runtime error: attempt to call ngx.redirect after sending out the headers
stack traceback:
coroutine 0:
	[C]: ?, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:11:45 [error] 57147#57147: *3 lua entry thread aborted: runtime error: attempt to call ngx.redirect after sending out the headers
stack traceback:
coroutine 0:
	[C]: ?, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:14:09 [error] 58539#58539: *1 lua entry thread aborted: runtime error: attempt to call ngx.redirect after sending out the headers
stack traceback:
coroutine 0:
	[C]: ?, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:14:27 [error] 59590#59590: *1 lua entry thread aborted: runtime error: attempt to call ngx.exec after sending out response headers
stack traceback:
coroutine 0:
	[C]: ?, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:17:46 [error] 64073#64073: *1 failed to load inlined Lua code: content_by_lua(nginx.conf:70):41: '=' expected near 'http', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:17:46 [error] 64073#64073: *2 failed to load inlined Lua code: content_by_lua(nginx.conf:70):41: '=' expected near 'http', client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:22:31 [error] 66960#66960: *1 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/core/exit.lua:52: bad argument #2 to 'ngx_lua_ffi_exit' (cannot convert 'nil' to 'int')
stack traceback:
coroutine 0:
	[C]: in function 'ngx_lua_ffi_exit'
	/usr/local/openresty/lualib/resty/core/exit.lua:52: in function 'exit'
	access_by_lua(nginx.conf:70):41: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:22:32 [error] 66960#66960: *3 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/core/exit.lua:52: bad argument #2 to 'ngx_lua_ffi_exit' (cannot convert 'nil' to 'int')
stack traceback:
coroutine 0:
	[C]: in function 'ngx_lua_ffi_exit'
	/usr/local/openresty/lualib/resty/core/exit.lua:52: in function 'exit'
	access_by_lua(nginx.conf:70):41: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:23:12 [emerg] 68054#68054: "proxy_pass" directive is not allowed here in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:20
2022/05/27 17:23:36 [error] 68087#68087: *1 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/core/exit.lua:52: bad argument #2 to 'ngx_lua_ffi_exit' (cannot convert 'nil' to 'int')
stack traceback:
coroutine 0:
	[C]: in function 'ngx_lua_ffi_exit'
	/usr/local/openresty/lualib/resty/core/exit.lua:52: in function 'exit'
	content_by_lua(nginx.conf:70):41: in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:25:06 [error] 70355#70355: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:26:36 [error] 73587#73587: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:26:39 [error] 73587#73587: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:26:40 [error] 73587#73587: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:26:41 [error] 73587#73587: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:26:41 [error] 73587#73587: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:28:50 [error] 76890#76890: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:28:51 [error] 76890#76890: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 17:37:38 [emerg] 83125#83125: directive "rewrite_by_lua" is not terminated by ";" in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:29
2022/05/27 17:38:15 [emerg] 83224#83224: directive "content_by_lua" is not terminated by ";" in /home/jiazhen/Desktop/ThrottlingDefender/ThrottlingDefender/nginx/conf/nginx.conf:29
2022/05/27 18:36:02 [error] 92292#92292: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:36:03 [error] 92292#92292: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:51:17 [error] 97601#97601: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:51:18 [error] 97601#97601: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:51:19 [error] 97601#97601: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:51:19 [error] 97601#97601: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:51:20 [error] 97601#97601: *1 attempt to set status 403 via ngx.exit after sending out the response status 200, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:53:42 [error] 99177#99177: *1 lua entry thread aborted: runtime error: rewrite_by_lua(nginx.conf:75):29: attempt to concatenate global 'full_url' (a nil value)
stack traceback:
coroutine 0:
	rewrite_by_lua(nginx.conf:75): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/27 18:55:33 [error] 101618#101618: *1 lua entry thread aborted: runtime error: rewrite_by_lua(nginx.conf:75):29: attempt to concatenate global 'full_url' (a nil value)
stack traceback:
coroutine 0:
	rewrite_by_lua(nginx.conf:75): in main chunk, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:50 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:50 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC647D0, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:50 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC647D0, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:51 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:51 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC64C48, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:51 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC64C48, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:51 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:51 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC65060, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:25:51 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC65060, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:10 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:10 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC65478, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:10 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC65478, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:11 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:11 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC65890, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:11 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC65890, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC65CA8, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC65CA8, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC660C0, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC660C0, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC664D8, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:12 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC664D8, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:13 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:13 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC668F0, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:13 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC668F0, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:13 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:13 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC66D08, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:13 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC66D08, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:14 [error] 17888#17888: *8 connect() failed (111: Connection refused), client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:14 [error] 17888#17888: *8 attempt to send data on a closed socket: u:00007F1C7FC67120, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:26:14 [error] 17888#17888: *8 attempt to receive data on a closed socket: u:00007F1C7FC67120, c:0000000000000000, ft:0 eof:0, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:28:30 [error] 17888#17888: *31 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:37:35 [error] 17888#17888: *46 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=tom&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 01:40:47 [error] 17888#17888: *94 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/28 01:43:01 [error] 17888#17888: *121 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/28 01:50:50 [error] 17888#17888: *132 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/register/ HTTP/1.1", host: "localhost:8080"
2022/05/28 02:15:17 [error] 17888#17888: *163 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 02:18:04 [error] 17888#17888: *170 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 02:21:46 [error] 17888#17888: *173 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 02:23:00 [error] 17888#17888: *173 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 02:23:31 [error] 17888#17888: *173 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 20:57:34 [error] 6229#6229: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 21:18:12 [error] 6229#6229: *86 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:14:35 [error] 6229#6229: *89 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:16:19 [error] 6229#6229: *92 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:18:26 [error] 6229#6229: *95 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:19:10 [error] 6229#6229: *95 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:30:29 [error] 6229#6229: *104 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:31:17 [error] 6229#6229: *104 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:33:31 [error] 6229#6229: *109 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:36:20 [error] 6229#6229: *112 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:37:33 [error] 6229#6229: *112 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:54:09 [error] 6229#6229: *119 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:56:52 [error] 6229#6229: *122 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 22:59:46 [error] 6229#6229: *125 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
2022/05/28 23:12:24 [error] 32116#32116: *1 lua tcp socket read timed out, client: 127.0.0.1, server: notes, request: "POST /users/login?username=jerry&password=12345 HTTP/1.1", host: "localhost:8080"
